name: Unit Tests

on: [push, pull_request]

jobs:
  build-linux:
    name: CI py${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.7', '3.8', '3.9', '3.10']
      max-parallel: 5

    steps:
    - uses: actions/checkout@v2

    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment:
            anaconda-test-env-py-${{ matrix.python-version }}
        auto-update-conda: true
        channel-priority: true
        channels: defaults,conda-forge,prjemian
        # environment-file: environment.yml
        mamba-version: "*"
        python-version: ${{ matrix.python-version }}
        use-only-tar-bz2: true  # required for caching
    - shell: bash -l {0}
      run: |
        conda info
        conda list
        conda config --show-sources
        conda config --show
        conda env list
        printenv | sort

    # $CONDA is an environment variable pointing to the
    # root of the miniconda directory

    - name: Install dependencies
      run: |
        mamba env update --file environment.yml --name $ENV_NAME
        mamba install coverage coveralls pytest pyyaml ruamel_yaml yaml setuptools-scm -c conda-forge --name $ENV_NAME
        mamba list -r --name $ENV_NAME
      env:
        PY_VER: ${{ matrix.python-version }}
        ENV_NAME: anaconda-test-env-py-${{ matrix.python-version }}

    - name: Diagnostic
      run: |
        mamba env list
        mamba list --name $ENV_NAME
      env:
        PY_VER: ${{ matrix.python-version }}
        ENV_NAME: anaconda-test-env-py-${{ matrix.python-version }}

    - name: Run tests with pytest & coverage
      run: |
        source $CONDA/bin/activate $ENV_NAME
        coverage run --concurrency=thread --parallel-mode -m pytest --lf -vvv .
        coverage combine
      env:
        PY_VER: ${{ matrix.python-version }}
        ENV_NAME: anaconda-test-env-py-${{ matrix.python-version }}

    - name: Coverage Report
      run: |
        source $CONDA/bin/activate $ENV_NAME
        coverage report -m --precision 3
      env:
        PY_VER: ${{ matrix.python-version }}
        ENV_NAME: anaconda-test-env-py-${{ matrix.python-version }}

    - name: Upload to coveralls
      # https://github.com/TheKevJames/coveralls-python
      run: |
        source $CONDA/bin/activate $ENV_NAME
        coveralls --service=github
      env:
        PY_VER: ${{ matrix.python-version }}
        ENV_NAME: anaconda-test-env-py-${{ matrix.python-version }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
